# Avoid ruby stuff
language: c
sudo: false

branches:
    only:
      - master

env:
  global:
    - INPUT_FILE=Slides.md
    - OUTPUT_FILE=index.html
    - GH_REPO=ivan-m/pandoc-slideshow
    - GH_BRANCH=gh-pages
    - secure: itEXc3+XkEdEx0OWDgxDRhQ9va8wRc7GP5t2AeJz6jLa7DoaiOF3HsbXGJJTJlmTcP7Bcj/u3IuyuWc/PveYBaJzxyTFrx/hwijClKCC8GNpaRZj0byYucyfWRmfRUx6s494xCACwb79UNIwjiZWyjOwGfELt2+EMcuIcCfDk0n1V8k022n/saIew+BLUD9afDHipCSDhJIDYx4FDOaNjK/bPOMPGFewvHBQ7ZWVX+yooKarvVYS5gycZp2ShoA0/suaw+iC6ve9YC9PFBvPmtNiRcraKfAK8t5hyP9+Wjj9o8mvtkMbOkUT1IuGzCJoWvx0c0JomazUJ0qzMRnsa4Ylgdd+gs1hYMpoMI8NJZMVnwk7AfnalQOflMv0XhWSz58vUt5xVcqhtraJFHsBNXQgxt5jStaWqXiSh/v+5GlBZ3BU53t7pHngtt6/mhoz3ZGE3w2dhJ41yyQT9ivpGTkcB6HjD/IRiyULReyX8NGYyzuEq2vN+/RmTLiwtcG2hQmqA8tEgMuwkGQFl7YrM3qfByZT95QOUw9deG0+m4uZNpm8W5PrDGkra7dGmeqtGcTTG44jvVStgD3H5zxOrzKAv16GLAA9tc8g9MYZkbp+2RRfyNaOUULz2ymOzbe45MDiwZLYPpWNsCH0HZYsi1ioILhI1AMnf5YaC9OYf+s=

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

before-cache:
  # Don't cache the Hackage index
  - rm -rf $HOME/.cabal/packages/hackage.haskell.org

branches:
  only:
    - master

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-2.2
      - ghc-8.4.2

before_install:
  - export PATH=$HOME/.cabal/bin:$(printf "%s:" /opt/ghc/*/bin)$(printf "%s:" /opt/cabal/*/bin)$PATH
  - travis_retry cabal update
  - travis_retry cabal install -j pandoc

script:
  - ./runPandoc.hs "${INPUT_FILE}" "${OUTPUT_FILE}"
  - git config --global user.email "Travis CI"
  - git config --global user.name "travis-ci@travis.org"
  - git clone --quiet --branch=$GH_BRANCH https://${GH_TOKEN}@github.com/$GH_REPO travis-build > /dev/null
  - cd travis-build
  # In case there's more images, etc.
  - git rebase origin/shared-data
  - cp ../"${OUTPUT_FILE}" .
  - git add -f .
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to GitHub Pages"
  - git push -fq origin $GH_BRANCH > /dev/null
